version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.7.0
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4513:4510-4513' # External services port range.
    environment:
      SERVICES: s3, sqs, iam
      AWS_ACCESS_KEY_ID: devAccessKeyId
      AWS_SECRET_ACCESS_KEY: devSecretAccessKey
      AWS_DEFAULT_REGION: us-east-1
      LS_LOG: ${LS_LOG:-debug}
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack:/etc/localstack/init/ready.d/'
